api.http.host: "0.0.0.0"
api.http.port: 9600

xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

pipeline.workers: 1
pipeline.batch.size: 125

# Pipeline configuration
config.reload.automatic: true
config.reload.interval: 3s
